# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               Work in progress
tagline:             'TODO: Implement taglone'
description:         'Description needed'
url:                 http://srdobos.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Steve Dobos
  url:               https://twitter.com/srdobos
  email:             srdobos@gmail.com

# Custom vars
version:             1.0.0
