# Permalinks
#
permalink:           pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               Code in progress
tagline:             'TODO: Implement tagline'
description:         'Thoughts, Ideas and Code about game dev'
url:                 http://srdobos.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Steve Dobos
  twitter:           https://twitter.com/srdobos
  email:             srdobos@gmail.com
  linkedin:          https://www.linkedin.com/in/stevedobos
  unityconnect:      https://connect.unity.com/u/582b993632b30600240003a4

# Custom vars
